### ISSUE TITLE
Auto1111 web ui extension

### ISSUE THREAD

**Issue by demirklvc** [YuxinWenRick/hard-prompts-made-easy#15]
Auto1111 web ui extension-is it possible?

**Comment by EmmaWebGH** [comment]
Hi
+1 to this
When you say it's integrated into the "unprompted" extension, I can't see on that page any info about PEZ being in unprompted's feature set. How is it integrated? Does unprompted add all of PEZ's functionality?

**Comment by YuxinWenRick** [comment]
Hi @EmmaWebGH, I found it [here](https://github.com/ThereforeGames/unprompted/blob/main/docs/MANUAL.md). The detailed summary is under `Stable Diffusion Shortcodes/[img2pez]`.

**Comment by EmmaWebGH** [comment]
@YuxinWenRick  Thank you!!
