### ISSUE TITLE
do you plan to create this for sd 1.5 too?

### ISSUE THREAD

**Issue by demirklvc** [YuxinWenRick/hard-prompts-made-easy#16]
.

**Comment by YuxinWenRick** [comment]
Hi, our code supports sd 1.5. The only change you need to make is the version of the CLIP model used for optimization. You may get more details [here](https://github.com/YuxinWenRick/hard-prompts-made-easy/issues/1#issuecomment-1421840150).

**Comment by demirklvc** [comment]
where do i have to change this please?: Hi, sorry for not including that important detail in the README file, but sure, you can use it for 1.5. SD 1.5 uses the text encoder of CLIP ViT-L/14 from OpenAI, so you can just simply change the argument by: args.clip_model = "ViT-L-14" and args.clip_pretrain = "openai". Also, if you are using the Jupyter notebook, you may also want to change model_id = "runwayml/stable-diffusion-v1-5" when loading the stable diffusion model.

**Comment by YuxinWenRick** [comment]
Hi, the easiest way to do this is to change the corresponding values in [sample_config.json](https://github.com/YuxinWenRick/hard-prompts-made-easy/blob/main/sample_config.json).

**Comment by demirklvc** [comment]
THANKS :)
