### ISSUE TITLE
[Feature] Can you make a simple UI for this?

### ISSUE THREAD

**Issue by StableInfo** [YuxinWenRick/hard-prompts-made-easy#22]
Hello,
Could you make a simple UI, maybe in gradio, for this?
This is one of the most impressive tools I knew and yet only few people know about it in the world of Stable diffusion etc.

Btw, is the prompt generating depending on a model or does it work in a "general" way? I mean can I select a model and obtain different prompts depending on the model? 
(Sorry I am not that AI technical to understand how it works in the details).

Thanks

**Comment by YuxinWenRick** [comment]
Hi, thanks for your interest,

As discussed [here](https://github.com/YuxinWenRick/hard-prompts-made-easy/issues/15#issuecomment-1536782867), there is a nice implementation from the community: https://github.com/r0mar0ma/sd-webui-pez-dispenser.

Yeah, if you are using different models, you may obtain different prompts.
