### ISSUE TITLE
[Discussion] Difference between different models? And other values?

### ISSUE THREAD

**Issue by StableInfo** [YuxinWenRick/hard-prompts-made-easy#23]
Hello, 
How to know what is the best model to choose from when trying to match the wanted prompt with the models we usually use (huggingface, civitai..) ?

**Comment by YuxinWenRick** [comment]
Hi, thanks for your interest!

Did you mean which CLIP model you should use for the prompt optimization?

There might not be a straightforward way to do so, but you can first check out the huggingface page of the diffusion model you are using to see what CLIP model they are using. For example, for [runwayml/stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5), if you search for "text encoder," you will see that they are using [CLIP ViT-L/14](https://arxiv.org/abs/2103.00020).

After you check the version of the CLIP model they used, you can modify the hyperparameter accordingly, as discussed [here](https://github.com/YuxinWenRick/hard-prompts-made-easy/issues/1) and [here](https://github.com/YuxinWenRick/hard-prompts-made-easy/issues/16).
