### ISSUE TITLE
import pez.open_clip problem? ModuleNotFoundError: No module named 'pez'

### ISSUE THREAD

**Issue by marseve** [YuxinWenRick/hard-prompts-made-easy#26]
I am using a fork of this.. and I am terrible at code, but I do use GPT to help LOL

anyway, when I run, it says "ModuleNotFoundError: No module named 'pez'"

![image](https://github.com/YuxinWenRick/hard-prompts-made-easy/assets/15349858/1f5038a4-f405-4658-a2d8-031fe97c8e34)

What code can I add to update? thanks!!!

**Comment by YuxinWenRick** [comment]
Hi, I assume you are running this on colab. You can cd to the repository first, and just import them, like:
```
!git clone https://github.com/YuxinWenRick/hard-prompts-made-easy
%cd hard-prompts-made-easy
import open_clip
from optim_utils import *
```

**Comment by marseve** [comment]
thanks!!! works!
