### ISSUE TITLE
reproduce result that only uses soft prompt

### ISSUE THREAD

**Issue by zhixiongzh** [YuxinWenRick/hard-prompts-made-easy#27]
Hi,

in the paper it is claimed that "We note that even though Stable Diffusion and CLIP share the same text encoder, soft prompts do not transfer well compared to all hard prompt methods in our evaluation".

How could I reproduce this soft prompt result with you code?  I guess I need to directly pass the soft prompt embedding to the Stable diffusion but not sure how to pass this to SD, as SD only support hard prompt as input. Even though the SD accepts prompt embedding as input, the format of this prompt embedding is different from the one you optimized.

Thanks in advance for any guidance.

**Comment by YuxinWenRick** [comment]
Hi, thanks for reaching out.

You can pass the soft prompt as [prompt_embeds](https://huggingface.co/docs/diffusers/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.__call__).

For the soft prompt optimization, you can simply don't do the forward projection: https://github.com/YuxinWenRick/hard-prompts-made-easy/blob/main/optim_utils.py#L163-L164, and do `projected_embeds = prompt_embeds`, and at the end, you can return `prompt_embeds` as the final soft prompt.

Let me know if you have further questions!

**Comment by zhixiongzh** [comment]
> Hi, thanks for reaching out.
> 
> You can pass the soft prompt as [prompt_embeds](https://huggingface.co/docs/diffusers/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.__call__).
> 
> For the soft prompt optimization, you can simply don't do the forward projection: https://github.com/YuxinWenRick/hard-prompts-made-easy/blob/main/optim_utils.py#L163-L164, and do `projected_embeds = prompt_embeds`, and at the end, you can return `prompt_embeds` as the final soft prompt.
> 
> Let me know if you have further questions!

@YuxinWenRick Thanks for the answer!

If this is how you transfer the soft prompt from the CLIP to Stable Diffusion, then it is a bug and thus your claim in the paper is not correctly verified.

The reason is, the `prompt_embeds` returned in your optimization code is the embedding without positional information and without processed by the text encoder (so it is just an embedding in the look up table). However, the `prompt_embeds` accepted by the Stable diffusion should be the embedding that has positional information and processed by the text encoder. That means, it is prompt features instead of prompt embedding(their name is misleading). Please refer to this [example](https://huggingface.co/docs/diffusers/v0.16.0/en/using-diffusers/weighted_prompts) given by official huggingface team. You can see that they use text encoder to process the hard prompt instead of from the "lookup table". Just print the `prompt_embs` they create, then you will find that the padding embedding is not the same, proving that it is not just `embedding` in the look up table but the features after feeding to the text encoder model.

**Comment by YuxinWenRick** [comment]
Hi, I think you are right. You need to pass it to the text encoder first. That's a nice catch.

I double-checked the code I implemented for the soft prompt experiments. Actually, what we did was to train a soft prompt and then project it to the nearest neighbor as a hard prompt. The diffusers version (v0.11.0) we were using actually didn't support `prompt_embeds` at that moment: https://github.com/huggingface/diffusers/blob/v0.11.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L409-L424. 

Meanwhile, we mentioned this in our paper: 
![image](https://github.com/user-attachments/assets/3b5372b3-c838-4ed9-93c8-130d8fa5575f), as we focus on discrete prompt optimization.

However, I am curious if the real soft prompts work. Have you tried it using the method you mentioned?

**Comment by zhixiongzh** [comment]
> Hi, I think you are right. You need to pass it to the text encoder first. That's a nice catch.
> 
> I double-checked the code I implemented for the soft prompt experiments. Actually, what we did was to train a soft prompt and then project it to the nearest neighbor as a hard prompt. The diffusers version (v0.11.0) we were using actually didn't support `prompt_embeds` at that moment: https://github.com/huggingface/diffusers/blob/v0.11.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L409-L424.
> 
> Meanwhile, we mentioned this in our paper: ![image](https://private-user-images.githubusercontent.com/32457665/351123946-3b5372b3-c838-4ed9-93c8-130d8fa5575f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzg3ODksIm5iZiI6MTcyMTkzODQ4OSwicGF0aCI6Ii8zMjQ1NzY2NS8zNTExMjM5NDYtM2I1MzcyYjMtYzgzOC00ZWQ5LTkzYzgtMTMwZDhmYTU1NzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDIwMTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTgwOTcxNDI1MWUzNWNkZTU4MjMxM2EzOTI0ZjkzYjA3NzA1Y2YyZTg1MTVmZDc2MTU2Y2U2NzQyMmRhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._9EpJYw0d1FeCkBNUPUVVpQe7xRDclJkSip0crKz4Yw), as we focus on discrete prompt optimization.
> 
> However, I am curious if the real soft prompts work. Have you tried it using the method you mentioned?

Thanks for the responsible double-check!

I did try the method, but I found the `prompt embedding` that the stable diffusion accept is still different from that processed by the method I mentioned, and can not find the reason yet. I leave it as a bug for now and continue with others. Anyway, thanks for the clarity!
