### ISSUE TITLE
gpu detection fails

### ISSUE THREAD

**Issue by unoriginalscreenname** [YuxinWenRick/hard-prompts-made-easy#8]
run.py fails to detect the gpu.  I have a 3090Ti and all the current drivers installed.  GPU detection works on everything else.

Also your instructions for activating the venv do not work as written.

**Comment by JonasGeiping** [comment]
Thanks for sharing! Just for our notes, is your OS windows 10/11?

**Comment by CT-Actual** [comment]
same issue here. Win 10 + 1080ti

**Comment by YuxinWenRick** [comment]
Hi, @CT-Actual, does including `torch==1.13.0+cu117` solve your problem?
